/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List shopping items */
        get: operations["listItems"];
        put?: never;
        /** Create a shopping item */
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The shopping item's MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Update a shopping item's bought status */
        put: operations["updateItem"];
        post?: never;
        /** Delete a shopping item */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API health */
        get: operations["checkHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ShoppingItem: {
            /** @example 507f1f77bcf86cd799439011 */
            id: string;
            /** @example Butter */
            name: string;
            /** @example false */
            bought: boolean;
            /**
             * Format: date-time
             * @example 2026-07-20T12:00:00.000Z
             */
            createdAt: string;
        };
        CreateShoppingItemRequest: {
            /** @example Butter */
            name: string;
        };
        UpdateShoppingItemRequest: {
            /** @example true */
            bought: boolean;
        };
        ErrorResponse: {
            /** @example about:blank */
            type: string;
            /** @example Bad Request */
            title: string;
            /** @example 400 */
            status: number;
            /** @example The request could not be validated */
            detail: string;
            /** @example /v1/health */
            instance: string;
            /** @example #ERR_VALIDATION_FAILED */
            code: string;
            errors?: components["schemas"]["ErrorDetail"][];
        };
        ErrorDetail: {
            /**
             * @example query
             * @enum {string}
             */
            source: "body" | "path" | "query" | "header" | "cookie";
            /**
             * @example [
             *       "name"
             *     ]
             */
            path: (string | number)[];
            /** @example String must contain at least 1 character */
            detail: string;
        };
        HealthResponse: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
            /** @example 0.0.1d */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The shopping items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingItem"][];
                };
            };
            /** @description The shopping items could not be retrieved */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShoppingItemRequest"];
            };
        };
        responses: {
            /** @description The shopping item was created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingItem"];
                };
            };
            /** @description The request is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The shopping item could not be created */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The shopping item's MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShoppingItemRequest"];
            };
        };
        responses: {
            /** @description The shopping item was updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingItem"];
                };
            };
            /** @description The request is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The shopping item was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The shopping item could not be updated */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The shopping item's MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The shopping item was deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The shopping item id is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The shopping item was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The shopping item could not be deleted */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    checkHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description The API could not complete the health check */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
